/*
 * Charlie Lew  
 * Date: March 28, 2016
 * Version:    v0.01
 * Description: This is a program that runs a slot machine with three numbers.
Starting number of coins: 50
Unlike three numbers: 0 coin 
All numbers are one: 4 coins
All numbers are two: 6 coins
All numbers are three: 8 coins
All numbers are four: 10 coins
If all the coins are lost, the game ends
 */
package ca.hdsb.gwss.charlielew.u4;

import java.awt.Color;

/**
 *
 * @author JinHwanCharlieLew
 */
public class SlotMachine extends javax.swing.JFrame {

    /**
     * Creates new form SlotMachine
     */
    public SlotMachine() {
        initComponents();
        labelCoin.setText(coin + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMid = new javax.swing.JPanel();
        buttonSpin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaOne = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaTwo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaThree = new javax.swing.JTextArea();
        panelDown = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelCoin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textFieldAnswer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Win or Lose Slot Machine");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Krungthep", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Slot Machine ");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMid.setBackground(new java.awt.Color(51, 255, 0));

        buttonSpin.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        buttonSpin.setText("Spin");
        buttonSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpinActionPerformed(evt);
            }
        });

        textAreaOne.setEditable(false);
        textAreaOne.setBackground(new java.awt.Color(0, 0, 0));
        textAreaOne.setColumns(1);
        textAreaOne.setFont(new java.awt.Font("Gill Sans", 1, 150)); // NOI18N
        textAreaOne.setForeground(new java.awt.Color(255, 255, 0));
        textAreaOne.setRows(1);
        jScrollPane2.setViewportView(textAreaOne);

        textAreaTwo.setEditable(false);
        textAreaTwo.setBackground(new java.awt.Color(0, 0, 0));
        textAreaTwo.setColumns(1);
        textAreaTwo.setFont(new java.awt.Font("Gill Sans", 1, 150)); // NOI18N
        textAreaTwo.setForeground(new java.awt.Color(255, 255, 0));
        textAreaTwo.setRows(1);
        jScrollPane3.setViewportView(textAreaTwo);

        textAreaThree.setEditable(false);
        textAreaThree.setBackground(new java.awt.Color(0, 0, 0));
        textAreaThree.setColumns(1);
        textAreaThree.setFont(new java.awt.Font("Gill Sans", 1, 150)); // NOI18N
        textAreaThree.setForeground(new java.awt.Color(255, 255, 0));
        textAreaThree.setRows(1);
        jScrollPane4.setViewportView(textAreaThree);

        javax.swing.GroupLayout panelMidLayout = new javax.swing.GroupLayout(panelMid);
        panelMid.setLayout(panelMidLayout);
        panelMidLayout.setHorizontalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(panelMidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMidLayout.setVerticalGroup(
            panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDown.setBackground(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Yuanti SC", 1, 24)); // NOI18N
        jLabel2.setText("Current Coin");

        labelCoin.setBackground(new java.awt.Color(0, 0, 0));
        labelCoin.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        labelCoin.setForeground(new java.awt.Color(255, 0, 0));
        labelCoin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textFieldAnswer.setEditable(false);
        textFieldAnswer.setBackground(new java.awt.Color(0, 0, 0));
        textFieldAnswer.setColumns(1);
        textFieldAnswer.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textFieldAnswer.setForeground(new java.awt.Color(255, 255, 255));
        textFieldAnswer.setRows(1);
        textFieldAnswer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(textFieldAnswer);

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelCoin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelDownLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCoin, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables
    int coin = 50;
    int lose = 0;
    int prize;
    private void buttonSpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpinActionPerformed

        // use 1 coin each time
        coin--;

        // First Number
        int firstSlot = (int) (Math.random() * 4) + 1;
        textAreaOne.setText(" " + firstSlot);

        // Second Number
        int secondSlot = (int) (Math.random() * 4) + 1;
        textAreaTwo.setText(" " + secondSlot);

        // Third Number
        int thirdSlot = (int) (Math.random() * 4) + 1;
        textAreaThree.setText(" " + thirdSlot);

        // LOSE
        if (firstSlot != secondSlot || secondSlot != thirdSlot) {
            textFieldAnswer.setText("Sorry!\n"
                    + "YOU WON " + lose + " TOKENS \n"
                    + "Try Again!!!");
            textAreaOne.setForeground(Color.red);
            textAreaTwo.setForeground(Color.red);
            textAreaThree.setForeground(Color.red);
        } // WIN
        else {
            prize = 2 * firstSlot + 2;
            coin = coin + prize;
            textFieldAnswer.setText("CONGRATULATIONS!\n"
                    + "YOU WON " + prize + " TOKENS \n"
                    + "Try Again!!!");
            textAreaOne.setForeground(Color.green);
            textAreaTwo.setForeground(Color.green);
            textAreaThree.setForeground(Color.green);
        }
        // No coin left
        if (coin == 0) {
            buttonSpin.setEnabled(false);
            textFieldAnswer.setText("YOU LOST");
            panelDown.setBackground(Color.red);
            panelMid.setBackground(Color.red);
        }
        // Final number of coins left
        labelCoin.setText("" + coin);
    }//GEN-LAST:event_buttonSpinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSpin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCoin;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelMid;
    private javax.swing.JTextArea textAreaOne;
    private javax.swing.JTextArea textAreaThree;
    private javax.swing.JTextArea textAreaTwo;
    private javax.swing.JTextArea textFieldAnswer;
    // End of variables declaration//GEN-END:variables
}
